## Configurations for a Residual Quantization (RQ) model with K-means at each layer.
## This model uses pre-computed embeddings as input.

defaults:
  - _self_

_target_: src.experimental.modules.clustering.residual_quantization.ResidualQuantization

track_residuals: true
verbose: true

train_layer_wise: true
normalize_residuals: true

input_dim: 4096  # The input dimension of the embeddings, 

n_layers: 3    # No of sids
init_buffer_size: 3072
quantization_layer:
  _target_: src.models.modules.clustering.mini_batch_kmeans.MiniBatchKMeans
  n_clusters: 256
  n_features: ${model.input_dim}
  distance_function:
    _target_: src.components.distance_functions.SquaredEuclideanDistance
  initializer:
    _target_: src.experimental.components.clustering_initializers.KMeansPlusPlusInitInitializer
    n_clusters: ${model.quantization_layer.n_clusters}
    distance_function: ${model.quantization_layer.distance_function}
    initialize_on_cpu: false
  init_buffer_size: ${model.init_buffer_size}

optimizer: ${optim.optimizer}
scheduler: null
quantization_layer_list: null

training_loop_function:
  _target_: src.experimental.components.training_loop_functions.scale_loss_by_world_size_for_initialization_training_loop
  _partial_: true
