## Configurations for a Residual Quantization Variational Autoencoder (RQ-VAE) model.
## This model takes pre-computed embeddings as input.

defaults:
  - _self_

_target_: src.experimental.modules.clustering.residual_quantization.ResidualQuantization

track_residuals: true
verbose: true

train_layer_wise: false
normalize_residuals: false

input_dim: 2048  # The input dimension of the embeddings

normalization_layer:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.BatchNorm1d
      num_features: ${model.input_dim}
    - _target_: src.models.components.network_blocks.normalize_layer.NormalizeLayer

encoder:
  _target_: src.models.components.network_blocks.mlp.MLP
  input_dim: ${model.input_dim}
  hidden_dim_list:
    - 768
    - 256
    - 128
  output_dim: 64
  activation:
    _target_: torch.nn.ReLU
    _partial_: true

decoder:
  _target_: src.models.components.network_blocks.mlp.MLP
  input_dim: ${model.encoder.output_dim}
  hidden_dim_list:
    - 128
    - 256
    - 768
  output_dim: ${model.input_dim}
  activation:
    _target_: torch.nn.ReLU
    _partial_: true

n_layers: 3
init_buffer_size: 3072
quantization_layer:
  _target_: src.experimental.modules.clustering.vector_quantization.VectorQuantization
  n_clusters: 256
  n_features: ${model.encoder.output_dim}
  distance_function:
    _target_: src.components.distance_functions.SquaredEuclideanDistance
  quantization_strategy:
    _target_: src.experimental.components.quantization_strategies.STEQuantization
    distance_function: ${model.quantization_layer.distance_function}
    compute_reconstruction_loss_embeddings: true
  initializer:
    _target_: src.experimental.components.clustering_initializers.ClusteringModuleInitializer
    n_clusters: ${model.quantization_layer.n_clusters}
    initialize_on_cpu: false
    clustering_module:
      _target_: src.models.modules.clustering.mini_batch_kmeans.MiniBatchKMeans
      n_clusters: ${model.quantization_layer.n_clusters}
      n_features: ${model.quantization_layer.n_features}
      distance_function: ${model.quantization_layer.distance_function}
      initializer:
        _target_: src.experimental.components.clustering_initializers.KMeansPlusPlusInitInitializer
        n_clusters: ${model.quantization_layer.n_clusters}
        distance_function: ${model.quantization_layer.distance_function}
        initialize_on_cpu: false
      init_buffer_size: ${model.init_buffer_size}
      update_manually: true
    max_iter: 1000
  init_buffer_size: ${model.init_buffer_size}
  loss_function:
    _target_: src.experimental.components.loss_functions.BetaQuantizationLoss
    beta: 0.25
    reduction: mean

reconstruction_loss_function:
  _target_: torch.nn.MSELoss
  reduction: mean
reconstruction_loss_weight: 1.0

training_loop_function:
  _target_: src.experimental.components.training_loop_functions.scale_loss_by_world_size_for_initialization_training_loop
  _partial_: true

optimizer: ${optim.optimizer}
scheduler: null
quantization_layer_list: null
